server:
  rootPath: '/api/*'
  applicationConnectors:
    - type: http
      port: 9951
      acceptorThreads: 1
      selectorThreads: 8
  adminConnectors:
    - type: http
      port: 9952
      acceptorThreads: 1
      selectorThreads: 8
  maxThreads: 256
  gzip:
    enabled: true
    bufferSize: 20KB

firstName: "John"
lastName: "Doe"